//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public OrderSet()
        {
            this.OrderRowSet = new HashSet<OrderRowSet>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<OrderRowSet> OrderRowSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
