//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRowSet
    {
        public int Id { get; set; }
        public long Quantity { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
    
        public virtual OrderSet OrderSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
