//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSet
    {
        public ProductSet()
        {
            this.OrderRowSet = new HashSet<OrderRowSet>();
            this.ReviewSet = new HashSet<ReviewSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string ShortDescription { get; set; }
        public string ImgUrl { get; set; }
        public double AverageRating { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
    
        public virtual CategorySet CategorySet { get; set; }
        public virtual ICollection<OrderRowSet> OrderRowSet { get; set; }
        public virtual ICollection<ReviewSet> ReviewSet { get; set; }
    }
}
